FROM amazoncorretto:21

# Definimos un directorio por defectopara trabajar
WORKDIR /java-test

# Copiamos de nuestro directorio, el Main.class a Docker
#COPY ./Main.java ./Main.java

# Creamos el archivo Main.class
# RUN javac Main.java

# Le decimos que ejecute el archivo tipo java, llamado "Main"
ENTRYPOINT [ "javac" ]

#prueba2